---

- name: Install Docker and Deploy Nginx
  hosts: servers
  become: true

  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Install Docker Compose plugin
      apt:
        name: docker-compose-v2
        state: present
        update_cache: yes

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Create application directory
      file:
        path: /opt/nginx
        state: directory
        mode: '0755'

    - name: Copy Docker Compose file
      copy:
        src: docker-compose.yml
        dest: /opt/nginx/docker-compose.yml

    - name: Start Nginx container
      command: docker compose up -d
      args:
        chdir: /opt/nginx
